"""Added log columns raw_soil, soil_type

Revision ID: c68489721029
Revises: 
Create Date: 2025-08-07 08:48:35.518292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c68489721029'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raw_soil', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('soil_type', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.drop_column('soil_type')
        batch_op.drop_column('raw_soil')

    # ### end Alembic commands ###
