"""added raw_calMin and raw_calMax fields

Revision ID: dfdc4d65256a
Revises: c68489721029
Create Date: 2025-08-10 19:44:29.644113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfdc4d65256a'
down_revision = 'c68489721029'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raw_calMin', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('raw_calMax', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.drop_column('raw_calMax')
        batch_op.drop_column('raw_calMin')

    # ### end Alembic commands ###
